### ISSUE TITLE
Having trouble with module ruled

### ISSUE THREAD

**Issue by cauna** [afreidz/dots#3]
Hi afrieds,
      After following your instruction, awesomewm fails to start and return with errof fiding package ruled. Is there a way to fix it? Much thanks!

**Comment by afreidz** [comment]
hmmm ... nothing jumps out at me at the moment. could you maybe post the full error stack?

**Comment by cauna** [comment]
Hi afreidz, it was fixed by rebuilding awesome from aur lol. Thanks tho. Brilliant setup!
